blank_issues_enabled: false
contact_links:
  - name: ğŸ“ rescript-lang.org
    url: https://github.com/rescript-association/rescript-lang.org/issues
    about: Please report problems about the documentation page here.
  - name: ğŸ’» rescript-vscode
    url: https://github.com/rescript-lang/rescript-vscode/issues
    about: VSCode language support, LSP, tools
  - name: ğŸ“¦ create-rescript-app
    url: https://github.com/rescript-lang/create-rescript-app/issues
    about: ReScript's project generator
  - name: âš›ï¸ rescript-react
    url: https://github.com/rescript-lang/rescript-react/issues
    about: ReScript bindings to React.js
  - name: ğŸŒ rescript-core
    url: https://github.com/rescript-association/rescript-core/issues
    about: New ReScript standard library
  - name: ğŸ’¬ ReScript Forum
    url: https://forum.rescript-lang.org/
    about: For discussions about ReScript, please visit the official ReScript forum.
